### ISSUE TITLE
Some Fixes/Recommendations

### ISSUE THREAD

**Issue by kev-cao** [spade-as-in-ace/time-logger#1]
Just some recommendations I would make to improve the script.

---

https://github.com/spade-as-in-ace/time-logger/blob/ba287f05b9e901571c37c7b355e1909c04cc0d59/scripts/time_logger.py#L17-L20

No need to close the file here since you're going to immediately open it back up right afterwards.

https://github.com/spade-as-in-ace/time-logger/blob/ba287f05b9e901571c37c7b355e1909c04cc0d59/scripts/time_logger.py#L25

Likewise with above, if you leave the file open, then you don't need to open it again here.

---

https://github.com/spade-as-in-ace/time-logger/blob/ba287f05b9e901571c37c7b355e1909c04cc0d59/scripts/time_logger.py#L52

Instead of closing the file at the end of each loop, may as well leave it open and close it after the loop terminates. It's inefficient to keep opening and closing the file.

---

https://github.com/spade-as-in-ace/time-logger/blob/ba287f05b9e901571c37c7b355e1909c04cc0d59/scripts/time_logger.py#L27

`log_file.name[:10]`? Indexing with negative indices is just over-complicating it in my opinion.

---

https://github.com/spade-as-in-ace/time-logger/blob/ba287f05b9e901571c37c7b355e1909c04cc0d59/scripts/time_logger.py#L34

Replace with `if keys[0] in KEYS:`.

---

https://github.com/spade-as-in-ace/time-logger/blob/ba287f05b9e901571c37c7b355e1909c04cc0d59/scripts/time_logger.py#L36-L37

Perhaps instead of shutting down the user's computer for them - just terminate the loop and close the files. An unnecessary feature to shutdown the computer for the user (especially since it's not difficult to do so), since the script is really just for logging times. 

Right now, there is no way for the user to stop the program other than force stopping it.

---

https://github.com/spade-as-in-ace/time-logger/blob/ba287f05b9e901571c37c7b355e1909c04cc0d59/scripts/time_logger.py#L51

Typo in "unrecognized".

---

https://github.com/spade-as-in-ace/time-logger/blob/ba287f05b9e901571c37c7b355e1909c04cc0d59/scripts/time_logger.py#L55

```py
if __name__ == "__main__":
```

Should be added before calling `main` function.

---

On startup, there is a bug where the first entry is not separated from the startup line:

```
startup, 20:14:53lunch, 20:14:57,
return, 20:14:59,
```

---

Ideally, there should be some sort of simple text UI. Also the different options should be displayed as well so that the user doesn't have to refer to the code to see what options they have.

**Comment by spade-as-in-ace** [comment]
To confess, I put this here just to share it with a few people, not so much to actually maintain it, so forgive my taking a year to see this comment.
I actually had fixed most of these things last year and just never uploaded the changes to git. I shall go point-by-point.

### Open/closing file:
I had other programs that would also open and modify the log files (in addition to doing it manually on occasion). This was the main reason the code opens the file, writes to it, then closes it. Further, it did not seem to make sense to leave a file open for long periods of time when I would at most be wanting to write some 40 chars to it over the course of 10 minutes every hour or two.

### String indexing:
The file path is something along the lines of `C:\\Users\\Spade\\Documents\\logs\\02-06-2021.csv`, of which only the `02-06-2021` section is needed, hence the need for such indexing.

### Checking dictionary:
Yes you are right - I was in Java-mode writing this so I let that slip. I had fixed this, but again failed to upload to git.

### Shutdown/Quit:
My work was all done within a terminal. I did this as a convenience to me. I rarely use my mouse when on a computer, instead using key-commands to flip around the place. That is why I had added the shutdown system call. I realized that there was no way to quit, so I had actually added a `q` command to quit, which I failed to upload.

### Typo/Missing-newline/\_\_name\_\_ == "\_\_main\_\_":
Again all things I had fixed but failed to upload.

### Regarding a UI:
I can see the need for a UI, so I may add a `h` or `help` flag to display the commands. I dislike having a terminal cluttered with help messages when I don't need them, and since I had written it originally for me, I obviously didn't need help understanding my own program. I will however add this.


### Addendum:
I actually threw myself even further down the hole of minimalist key-binds and will be adding a separate version of this script here designed to be triggered by key commands, e.g. `ctrl+alt+b` to log a "break"  rather than having a single `while True` loop.
